allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  '@stellar/stellar-sdk': set this to true or false
  bigint-buffer: set this to true or false
  blake-hash: set this to true or false
  bufferutil: true
  prisma: true
  protobufjs: set this to true or false
  sharp: true
  tiny-secp256k1: set this to true or false
  usb: set this to true or false
  utf-8-validate: true
onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - bigint-buffer
  - bufferutil
  - prisma
  - sharp
  - utf-8-validate
