//! # Trident Generated Types
//!
//! This file is automatically generated by Trident.
//! **DO NOT EDIT THIS FILE MANUALLY**

#![allow(dead_code)]
#![allow(unused_imports)]

use borsh::BorshDeserialize;
use borsh::BorshSerialize;
use trident_fuzz::fuzzing::*;

// ============================================================================
// PROGRAM MODULES
// ============================================================================

// ----------------------------------------------------------------------------
// Program: staking
// ----------------------------------------------------------------------------
pub mod staking {
    use super::*;

    // ------------------------------------------------------------------------
    // Program ID
    // ------------------------------------------------------------------------

    /// Returns the program ID for staking
    pub fn program_id() -> Pubkey {
        pubkey!("8zcJ4P4TrFNuL3p3BUNXtWP22rfPaVj5CJzMW4exgXen")
    }

    // ------------------------------------------------------------------------
    // Instructions
    // ------------------------------------------------------------------------

    // ....................................................................
    // Instruction: CreatePool
    // ....................................................................

    /// Main instruction struct for CreatePool
    pub struct CreatePoolInstruction {
        pub accounts: CreatePoolInstructionAccountMetas,
        pub data: CreatePoolInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for CreatePool instruction
    #[derive(Debug, Clone, Default)]
    pub struct CreatePoolInstructionAccountMetas {
        pub authority: AccountMeta,

        pub global_config: AccountMeta,

        pub pool: AccountMeta,

        pub stake_mint: AccountMeta,

        pub reward_mint: AccountMeta,

        pub stake_vault: AccountMeta,

        pub reward_vault: AccountMeta,

        pub token_program: AccountMeta,

        pub system_program: AccountMeta,

        pub rent: AccountMeta,
    }

    /// Account pubkeys for CreatePool instruction
    #[derive(Debug, Clone)]
    pub struct CreatePoolInstructionAccounts {
        pub authority: Pubkey,

        pub global_config: Pubkey,

        pub pool: Pubkey,

        pub stake_mint: Pubkey,

        pub reward_mint: Pubkey,

        pub stake_vault: Pubkey,

        pub reward_vault: Pubkey,
    }

    impl CreatePoolInstructionAccounts {
        pub fn new(
            authority: Pubkey,

            global_config: Pubkey,

            pool: Pubkey,

            stake_mint: Pubkey,

            reward_mint: Pubkey,

            stake_vault: Pubkey,

            reward_vault: Pubkey,
        ) -> Self {
            Self {
                authority,

                global_config,

                pool,

                stake_mint,

                reward_mint,

                stake_vault,

                reward_vault,
            }
        }
    }

    /// Instruction data for CreatePool
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct CreatePoolInstructionData {
        pub apr_bps: u16,

        pub lock_duration: i64,

        pub cooldown_duration: i64,

        pub deposit_cap: u64,
    }

    impl CreatePoolInstructionData {
        pub fn new(
            apr_bps: u16,

            lock_duration: i64,

            cooldown_duration: i64,

            deposit_cap: u64,
        ) -> Self {
            Self {
                apr_bps,

                lock_duration,

                cooldown_duration,

                deposit_cap,
            }
        }
    }

    /// Implementation for CreatePoolInstruction
    impl CreatePoolInstruction {
        fn discriminator() -> [u8; 8] {
            [233u8, 146u8, 209u8, 142u8, 207u8, 104u8, 64u8, 188u8]
        }

        pub fn data(data: CreatePoolInstructionData) -> Self {
            Self {
                accounts: CreatePoolInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: CreatePoolInstructionAccounts) -> Self {
            self.accounts.authority = AccountMeta::new(accounts.authority, true);

            self.accounts.global_config = AccountMeta::new(accounts.global_config, false);

            self.accounts.pool = AccountMeta::new(accounts.pool, false);

            self.accounts.stake_mint = AccountMeta::new_readonly(accounts.stake_mint, false);

            self.accounts.reward_mint = AccountMeta::new_readonly(accounts.reward_mint, false);

            self.accounts.stake_vault = AccountMeta::new(accounts.stake_vault, false);

            self.accounts.reward_vault = AccountMeta::new(accounts.reward_vault, false);

            self.accounts.token_program = AccountMeta::new_readonly(
                pubkey!("TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"),
                false,
            );

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self.accounts.rent = AccountMeta::new_readonly(
                pubkey!("SysvarRent111111111111111111111111111111111"),
                false,
            );

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.authority.clone());

            metas.push(self.accounts.global_config.clone());

            metas.push(self.accounts.pool.clone());

            metas.push(self.accounts.stake_mint.clone());

            metas.push(self.accounts.reward_mint.clone());

            metas.push(self.accounts.stake_vault.clone());

            metas.push(self.accounts.reward_vault.clone());

            metas.push(self.accounts.token_program.clone());

            metas.push(self.accounts.system_program.clone());

            metas.push(self.accounts.rent.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ------------------------------------------------------------------------
    // Composite Accounts
    // ------------------------------------------------------------------------
}

// ============================================================================
// CUSTOM TYPES
// ============================================================================

/// Custom struct: GlobalConfig
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct GlobalConfig {
    pub admin_authority: Pubkey,

    pub pause_authority: Pubkey,

    pub treasury: Pubkey,

    pub bump: u8,

    pub version: u8,
}

impl GlobalConfig {
    pub fn new(
        admin_authority: Pubkey,

        pause_authority: Pubkey,

        treasury: Pubkey,

        bump: u8,

        version: u8,
    ) -> Self {
        Self {
            admin_authority,

            pause_authority,

            treasury,

            bump,

            version,
        }
    }
}

/// Custom struct: Pool
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct Pool {
    pub stake_mint: Pubkey,

    pub reward_mint: Pubkey,

    pub stake_vault: Pubkey,

    pub reward_vault: Pubkey,

    pub apr_bps: u16,

    pub lock_duration: i64,

    pub cooldown_duration: i64,

    pub deposit_cap: u64,

    pub paused: bool,

    pub total_staked: u64,

    pub acc_reward_per_share: u128,

    pub last_update_timestamp: i64,

    pub reward_rate_per_second: u64,

    pub total_rewards_funded: u64,

    pub bump: u8,

    pub version: u8,
}

impl Pool {
    pub fn new(
        stake_mint: Pubkey,

        reward_mint: Pubkey,

        stake_vault: Pubkey,

        reward_vault: Pubkey,

        apr_bps: u16,

        lock_duration: i64,

        cooldown_duration: i64,

        deposit_cap: u64,

        paused: bool,

        total_staked: u64,

        acc_reward_per_share: u128,

        last_update_timestamp: i64,

        reward_rate_per_second: u64,

        total_rewards_funded: u64,

        bump: u8,

        version: u8,
    ) -> Self {
        Self {
            stake_mint,

            reward_mint,

            stake_vault,

            reward_vault,

            apr_bps,

            lock_duration,

            cooldown_duration,

            deposit_cap,

            paused,

            total_staked,

            acc_reward_per_share,

            last_update_timestamp,

            reward_rate_per_second,

            total_rewards_funded,

            bump,

            version,
        }
    }
}

// ============================================================================
// END OF GENERATED FILE
// ============================================================================
